version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
    command: flask run --host=0.0.0.0 --port=5001